### ISSUE TITLE
Add file upload (POST) example to documentation/examples

### ISSUE THREAD

**Issue by dgollub** [Hexilee/roa#1]
Hi,

Pretty neat project. I just can not for the live of me figure out how to add an endpoint that handles file uploads via POST.

Could you maybe add an example to the documentation and/or examples folder on how to add such an endpoint that handles a file upload via POST (no DTO, but a raw file, e.g. PDF or XML etc)?

Thanks!

**Comment by Hexilee** [comment]
Handle a raw file, and save it?

**Comment by Hexilee** [comment]
https://github.com/Hexilee/roa/blob/master/examples/file-upload.rs
@dgollub This is a rough file upload example, as rao does not support multipart-form right now.

**Comment by dgollub** [comment]
@Hexilee Thanks for the example!

>  Does just handle a raw file, and save it?

Actually, the POST request right now would be `Content-Type: multipart/form-data`. Any idea how long it would take to add support for this to roa?

In the meantime, I'll see if the other team I work with can change their POST request for roa to work.

**Comment by Hexilee** [comment]
The multipart-async crate depends on futures-preview whose version is incompatible with dependencies of roa, and I was waiting for its upgrading earlier.

However, the author seems to having given up that project, I'm going to reimplementing mutipart form-data this week.

**Comment by dgollub** [comment]
Cool. Thanks. You can close this issue then. 👍

**Comment by Hexilee** [comment]
I will keep this issue open until multipart is implemented.

**Comment by Hexilee** [comment]
An [example](https://github.com/Hexilee/roa/tree/master/integration/multipart-example).
This example depends on roa v0.5.0-alpha which is not published. You can use git dependencies to play with it.
@dgollub

**Comment by dgollub** [comment]
@Hexilee Thanks. I gave it a try, once in my own code and once with your repository (master branch).

I used Chrome and the `assets/index.html` file on the `http://localhost:8000/` endpoint provided in this example and uploaded a simple PNG file.

In both cases I run into a crash/error when this line is reached:

`io::copy(&mut field.into_async_read(), &mut file).await?`

The error is

```
 Finished dev [unoptimized + debuginfo] target(s) in 1m 37s
     Running `/Users/dkg/projects/others/roa/target/debug/multipart-example`
 INFO  multipart_example > Server is listening on 127.0.0.1:8000
 INFO  roa::logger       > --> GET /
 INFO  roa::logger       > <-- GET / 1ms 240 B 200 OK
 INFO  roa::logger       > --> POST /file
 INFO  multipart_example > image/png
thread 'async-std/executor' panicked at 'Receiver::next_message called after `None`', src/libcore/option.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Abort trap: 6
```

I am on macOS 10.14.6 (18G1012) and my Rust compiler is `rustc 1.41.0 (5e1a79984 2020-01-27)`.

I tried changing the code to this, to see if it helps, but the error still happens when I do that:

```
match io::copy(&mut field.into_async_read(), &mut file).await {
    Ok(f) => info!("Got: {:?}", f),
    Err(err) => info!("Error {}", err),
};
```

Any idea what I am doing wrong?

**Comment by Hexilee** [comment]
it seems channel receiver of futures is not initialized successfully. As [source code](https://github.com/rust-lang/futures-rs/blob/c19d43f750856904ff66e3d06b293185e2729b84/futures-channel/src/mpsc/mod.rs#L1011), it may be a bug of futures.

**Comment by Hexilee** [comment]
@dgollub I cannot reproduce this bug. Could you find the upper panic point in async-std or actix by debug utility like lldb?

**Comment by dgollub** [comment]
@Hexilee Here is the stack trace I got when running `RUST_BACKTRACE=1 RUST_LOG=info cargo run > output.txt 2>&1`. I uploaded a GIF file this time, but same effect.

[output.txt](https://github.com/Hexilee/roa/files/4253756/output.txt)

**Comment by dgollub** [comment]
@Hexilee Here is the stack trace I got when running `RUST_BACKTRACE=full RUST_LOG=info cargo run > output.txt 2>&1`. Same GIF file.

[output-full.txt](https://github.com/Hexilee/roa/files/4253773/output-full.txt)

**Comment by Hexilee** [comment]
It was highly likely a bug  of `hyper::Body`，[this line](https://github.com/hyperium/hyper/blob/master/src/body/body.rs#L267) used an uninitialized receiver. Maybe you should create an issue in hyper project.

**Comment by dgollub** [comment]
Thanks @Hexilee. I opened a bug with hyper: [2141](https://github.com/hyperium/hyper/issues/2141). Maybe they can help.

**Comment by Hexilee** [comment]
I reproduce it now...
It's my fault, 'Receiver::next_message called after `None`' means receiver is closed instead of uninitialized. 
So, it should be a bug of actix-multipart, maybe it poll hyper body after Poll::Ready(None) is returned.
You can close [2141](https://github.com/hyperium/hyper/issues/2141) now, I fix it or discard actix-multipart .

**Comment by Hexilee** [comment]
It should work now.  The `actix_multipart::Multipart` is conflict against `hyper::Body`. 

As `actix_multipart::Multipart` uses a buffer to wrap `hyper::Body`,  

`actix_multipart::Field::poll_next` will return `Poll::Ready(Some(OK(bytes)))` after `hyper::Body::poll_next` returning `Poll::Ready(None)`. 

Then `actix_multipart::Field::poll_next` tries to poll `hyper::Body` again and crash.

**Comment by Hexilee** [comment]
It should work now.  The `actix_multipart::Multipart` is conflict against `hyper::Body`. 

As `actix_multipart::Multipart` uses a buffer to wrap `hyper::Body`,  

`actix_multipart::Field::poll_next` will return `Poll::Ready(Some(OK(bytes)))` after `hyper::Body::poll_next` returning `Poll::Ready(None)`. 

Then `actix_multipart::Field::poll_next` tries to poll `hyper::Body` again and crash.

**Comment by dgollub** [comment]
Cool, thanks. Sorry for the late response. I tested it with the latest master branch of roa and it works nicely. I'll close this issue now.
