### ISSUE TITLE
JSON-RPC Middleware?

### ISSUE THREAD

**Issue by gschmottlach-xse** [Hexilee/roa#12]
This is more of a question than an issue. Is there a JSON-RPC binding that is compatible with this crate? Coming from a Node.js background, Roa's similarities to Koa.js is very appealing. For my application, however, one thing that seems to be missing is easy JSON-RPC support and integration. Are you aware of any options that would work? I ran across [JsonRpc-v2](https://github.com/kardeiz/jsonrpc-v2) and hoped since it already offers Hyper integration it might be a candidate to use with Roa. Unfortunately,  it appears it may not be a simple drop-in middleware component. Have you given JSON-RPC support any consideration?

Thanks for sharing Roa!

**Comment by Hexilee** [comment]
The [`jsonrpc_v2::Server::handle`](https://docs.rs/jsonrpc-v2/0.5.2/jsonrpc_v2/struct.Server.html#method.handle) seems convenient to implement `roa::core::Endpoint`. However, I'm not convenient to do it before July, maybe you can try it by yourself and create a PR if it works.

**Comment by gschmottlach-xse** [comment]
Thanks for steering me towards investigating [jsonrpc_v2::Server::handle](https://docs.rs/jsonrpc-v2/0.5.2/jsonrpc_v2/struct.Server.html#method.handle). I was able to create a custom Endpoint and basically let that function handle decoding the request and producing a response. It was a fairly straightfoward implementation. Likely you could make it a more standardized and integrated feature of your crate with a little work. Unfortunately, I'm a Rust newbie/novice so I suspect any contributions I might make wouldn't pass muster with a more seasoned Rustacean. Regardless, I just wanted to let you know your suggestion works and thank you for your insights.

**Comment by Hexilee** [comment]
Hi, it seems [jsonrpc](https://github.com/paritytech/jsonrpc) is more mature than [jsonrpc-v2](https://github.com/kardeiz/jsonrpc-v2), I want to know the reason you choose the latter one. @gschmottlach-xse

**Comment by gschmottlach-xse** [comment]
Honestly, I'm not sure why I chose jsonrpc-v2 rather than jsonrpc. I was looking for a simple library that would integrate well with ROA using hyper and async-std. Certainly jsonrpc offers more features than jsonrpc-v2 and the additional transport servers is a major bonus. If you believe it (jsonrpc) offers an easier/better integration pathway for ROA then I certainly wouldn't discourage you from supporting it directly. At the time, jsonrpc-v2 seemed to offer decent features and your suggestion allowed me to integrate it into my test application. If you can do better with a different jsonrpc framework then feel free to pursue it. I'm sure everyone will benefit from your efforts.

Thanks . . .

**Comment by Hexilee** [comment]
Ok, maybe `jsonrpc-v2` is enough. I released [roa-jsonrpc](https://github.com/Hexilee/roa/tree/master/roa-jsonrpc), are there other features need to be integrated? I am not very familiar with jsonrpc.

**Comment by gschmottlach-xse** [comment]
I suspect (ultimately) jsonrpc offers more/better features (espeically the additional transports) vs. jsonrpc-v2 but for the demo I was working on jsonrpc-v2 was good enough. Perhaps you can consider supporting it (jsonrpc-v2) in the future if it's still compatible with hyper and async-std. I'm not a JSON RPC expert either but have had some experience with it in other Node.js based projects.

Thanks for making roa-jsonrpc available. I certainly appreciate it.

**Comment by Hexilee** [comment]
Well, I will close this issue.
