### ISSUE TITLE
Sending/Receiving individual Websocket messages?

### ISSUE THREAD

**Issue by gschmottlach-xse** [Hexilee/roa#13]
I have been investigating using Roa and websockets to support transferring JSON-RPC requests/responses.  The Roa websocket example simply echos all incoming messages back out to the sender, e.g.

```
async fn ws_handler( ctx: &mut Context<State>, stream: &mut SocketStream) -> () {
    let (write, mut read) = stream.split();
    if let Err(err) = read.forward(write).await {
         eprintln!("Forward error: {}", err);
 }
```
Messages are forwarded as long as the websocket remains opened.

In order to get at the individual Websocket messages and decode the JSON-RPC request contained within the message I turned to using the `next()` method to iteratate over the incoming messages, e.g.

```
async fn ws_handler( ctx: &mut Context<State>, stream: &mut SocketStream) -> () {
    let (write, mut read) = stream.split();
    let mut msgs: Vec<StdResult<Message, _>> = vec![];

    if let Some(item) = read.next().await {
        let data = item.unwrap();
        let resp = ctx.rpc_server.handle(data.into_data().as_slice()).await;
        let json_resp = serde_json::to_string(&resp).unwrap();
        msgs.push(Ok(Message::text(json_resp)));
    }

    if msgs.len() > 0 {
        let json_stream = futures_util::stream::iter(msgs);
        if let Err(err) = json_stream.forward(write).await {
            eprintln!("Forward error: {}", err);
        }
    }
}
```

This works fine but can only process a single request followed by a response before flushing and closing the websocket port (using the `forward()` method). There does not appear to be an easy way to keep the stream open and process multiple requests and return their associated responses without flushing and closing the stream.  For the `write` stream there needs to be an *awaitable* function to send and flush an individual message **without** closing the socket. Is there a method to do this that I am missing? Ideally, I might want to handle more than one JSON-RPC request/response before closing the stream. The above implementation will only process a single request/response pair before closing the socket. It seems like a very inefficent approach for handling multple JSON-RPC requests due to the overhead of executing the websocket handshake for every request. Can you provide a websocket example that does more than forwards/echoes  the incomming message back out? Ideally, there might be a way to insert a transform operation between the read/write streams that reads the JSON-RPC request and transforms it into a JSON-RPC response before forwarding it to the write steam. Can this be done with websockets as they're integrated into Roa?

Thanks . . .

**Comment by Hexilee** [comment]
Just use this in loop:

```rust
write.send(Message::text(json_resp)).await
```

Maybe you should add `use futures::SinkExt` to use the `send` method.

**Comment by Hexilee** [comment]
By the way, you can just use HTTP2 for better performance.

**Comment by gschmottlach-xse** [comment]
Thanks for the feedback. I'm still new to Rust and was unaware of the `futures:SinkExt` trait and didn't realize the `write` stream supported it. I used your suggestion and it seems to work as I expected. 

Is there anything I need to configure specifically in Roa to take advantage of HTTP2? Honestly, I am not familiar with the improvements so it looks like I have more research to do. Thanks for your suggestions . . . they've saved me a lot of time.

I'm surprised this web framework isn't promoted more like Warp or Tide. Seems to check a lot of the boxes and more. Thanks for making this available and the continued development and support.

**Comment by Hexilee** [comment]
As `hyper` support HTTP2 by default, You can just use an HTTP2 client without configuring.

**Comment by Hexilee** [comment]
I will close this issue if you don't have other probleams.

**Comment by gschmottlach-xse** [comment]
You can go ahead and close this issue. Thanks again for the support!
