### ISSUE TITLE
I dont like dsl(diesel) how to integrate roa with sqlx

### ISSUE THREAD

**Issue by adals** [Hexilee/roa#3]
above
[https://github.com/launchbadge/sqlx](https://github.com/launchbadge/sqlx)
thanks

**Comment by Hexilee** [comment]
Simply add `sqlx::Pool` in `State`, you can refer to example of [`roa::pg`](https://github.com/Hexilee/roa/blob/master/roa/src/pg.rs).
You can also just use `roa::pg`, I may add a sqlx integration in several days.
> Currently wiki is out of date, you'd better refer to examples and rust docs for correct documentation.

**Comment by adals** [comment]
@Hexilee Thanks
