### ISSUE TITLE
no method named `read_json` 

### ISSUE THREAD

**Issue by Inx6** [Hexilee/roa#38]
no method named `read_json` found for mutable reference `&mut roa::Context` in the current scope

**Comment by Hexilee** [comment]
Sorry for late reply, you should enable feature `json`, then please use `roa::body::PowerBody` or `roa::preload::PowerBody` to import this method.

**Comment by Hexilee** [comment]
According to https://docs.rs/roa/latest/roa/body/trait.PowerBody.html#required-methods
